# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5ebae9b937e56648570a05de2273cc3aafc26a411fb89a09b1f3c650696587d51edd225362b3cfa325fe35caa4cbec512842338feb36697c268bc6e3766b9ba

test:
  secret_key_base: 6646fcb80934d25842a573c7d43381f3575f97a5e23718e1a6b0c2862b398d3450863bd0dd8dafff36616f50cb1a0c77ccd2274fca43577adcd38ab9808b92d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
